<?php

namespace ContainerDE8jYzD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XPOfPW1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xPOfPW1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xPOfPW1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousCategorieRepository' => ['privates', 'App\\Repository\\SousCategorieRepository', 'getSousCategorieRepositoryService', true],
        ], [
            'sousCategorieRepository' => 'App\\Repository\\SousCategorieRepository',
        ]);
    }
}
