<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDE8jYzD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDE8jYzD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDE8jYzD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDE8jYzD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDE8jYzD\App_KernelDevDebugContainer([
    'container.build_hash' => 'DE8jYzD',
    'container.build_id' => '17634524',
    'container.build_time' => 1677226376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDE8jYzD');
